// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PMS.Repository.Models;

public partial class SaleOrder
{
    public int SaleOrderId { get; set; }

    public int CustomerId { get; set; }

    public string OrderNo { get; set; }

    public DateTime OrderDate { get; set; }

    public string ShipAddress { get; set; }

    public DateTime? ShipDate { get; set; }

    public decimal SubAmount { get; set; }

    public decimal Vatrate { get; set; }

    public decimal Vatamount { get; set; }

    public decimal TotalAmount { get; set; }

    public int Status { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<SaleOrderDetail> SaleOrderDetails { get; set; } = new List<SaleOrderDetail>();
}